/* empty css                      */import{a as m}from"./assets/vendor-3cGtQH5P.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))i(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const c of n.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function s(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerPolicy&&(n.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?n.credentials="include":r.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function i(r){if(r.ep)return;r.ep=!0;const n=s(r);fetch(r.href,n)}})();const t={body:document.querySelector("body"),burgerMenu:document.querySelector("[data-menu-open]"),menuOverlay:document.querySelector("[data-menu-overlay]"),mobileMenu:document.querySelector("[data-menu]"),mobileNavLinks:document.querySelectorAll("[data-menu-link]"),headerNavLinks:document.querySelectorAll(".header-nav-link"),navBtnDark:document.querySelector(".nav-btn-dark"),sections:document.querySelectorAll("section[id]"),categoriesList:document.querySelector("#categoriesGrid")};function f(){t.burgerMenu.classList.toggle("active"),t.menuOverlay.classList.toggle("is-open"),t.mobileMenu.classList.toggle("active"),t.body.classList.toggle("no-scroll"),t.burgerMenu.blur()}function u(){t.burgerMenu.classList.remove("active"),t.menuOverlay.classList.remove("is-open"),t.mobileMenu.classList.remove("active"),t.body.classList.remove("no-scroll"),t.burgerMenu.blur()}const v="https://furniture-store-v2.b.goit.study/api",p={CATEGORIES:"/categories",FURNITURES:"/furnitures"};m.defaults.baseURL=v;async function b(){const{data:e}=await m.get(p.CATEGORIES);return e}const a=["../img/our-furniture/img1.webp","../img/our-furniture/img2.webp","../img/our-furniture/img3.webp","../img/our-furniture/img4.webp","../img/our-furniture/img5.webp","../img/our-furniture/img6.webp","../img/our-furniture/img7.webp","../img/our-furniture/img8.webp","../img/our-furniture/img9.webp","../img/our-furniture/img10.webp","../img/our-furniture/img11.webp","../img/our-furniture/img12.webp","../img/our-furniture/img13.webp"];async function y(){try{const e=await b(),o=t.categoriesList,s=l({name:"Всі товари",_id:"",image:a[0]});o.appendChild(s),e.forEach((i,r)=>{const n=r+1,c=a[n]||a[0],g=l({name:i.name,_id:i._id,image:c});o.appendChild(g)})}catch(e){console.error("Помилка при рендері категорій:",e)}}function l({name:e,_id:o,image:s}){const i=document.createElement("li");return i.className="category-card",i.dataset.category=o||"",i.innerHTML=`
    <picture>
      <source srcset="${s.replace(".webp","@2x.webp")}" media="(min-resolution: 2dppx)">
      <img src="${s}" alt="${e}" class="category-img" loading="lazy">
    </picture>
    <div class="category-overlay">
      <h3 class="category-name">${e}</h3>
    </div>
  `,i}t.burgerMenu.addEventListener("click",f);t.mobileNavLinks.forEach(e=>e.addEventListener("click",u));t.menuOverlay.addEventListener("click",e=>{e.target.closest(".mobile-menu")||u()});document.addEventListener("keydown",e=>{e.key==="Escape"&&t.mobileMenu.classList.contains("active")&&u()});t.headerNavLinks.forEach(e=>e.addEventListener("click",o=>{o.preventDefault();const s=e.getAttribute("href").slice(1),i=document.getElementById(s);i&&i.scrollIntoView({behavior:"smooth"}),t.headerNavLinks.forEach(r=>r.classList.remove("active")),e.classList.add("active")}));const L=new IntersectionObserver(e=>{e.forEach(o=>{if(o.isIntersecting){t.headerNavLinks.forEach(i=>i.classList.remove("active"));const s=document.querySelector(`.header-nav-link[href="#${o.target.id}"]`);s&&s.classList.add("active")}})},{threshold:.5});t.sections.forEach(e=>L.observe(e));var d;(d=t.navBtnDark)==null||d.addEventListener("click",()=>{t.headerNavLinks.forEach(e=>e.classList.remove("active"))});document.addEventListener("DOMContentLoaded",()=>{y()});
//# sourceMappingURL=index.js.map
